packages:
  - packages/*

allowBuilds:
  '@fission-ai/openspec': true
  yo: true

catalogs:
  dev:
    '@fission-ai/openspec': ^1.5.0
    '@tofrankie/action': ^0.0.8
    '@tofrankie/commitlint': ^0.0.6
    '@tofrankie/eslint': ^0.4.1
    '@tofrankie/prettier': ^0.2.0
    '@tofrankie/tsconfig': ^0.2.1
    '@types/node': ^22.15.0
    commitlint: ^21.2.0
    eslint-doc-generator: ^3.6.0
    eslint-plugin-eslint-plugin: ^7.3.2
    generator-eslint: ^6.1.0
    husky: ^9.1.7
    lint-staged: ^17.0.8
    npm-run-all2: ^9.0.2
    prettier: ^3.9.4
    publint: ^0.3.21
    tsdown: ^0.22.3
    typescript: ^5.9.3
    yo: ^7.0.1
  peer:
    eslint: ^10.6.0
  prod:
    '@typescript-eslint/utils': ^8.62.1
  test:
    '@typescript-eslint/rule-tester': ^8.62.1
    vitest: ^4.1.9
